//go:build integration

// Focused integration test for the nil-Metadata validation bug (fix round
// 1): every collection's $jsonSchema validator, auto-generated by grove from
// the model's Go types, typed Metadata (and, for policy and resource_type,
// several other map/slice fields) as strictly "object"/"array". grove's
// insert path (structToMapInsert) always writes every struct field into the
// document regardless of its Go zero value — it doesn't honor `omitempty` —
// so a caller who never set Metadata sent BSON null on the wire and MongoDB
// rejected the insert with "Document failed validation". store/mongo/models.go
// now normalizes these fields to non-nil empty values before insert
// (nonNilMap/nonNilSlice), and the nullable_object_fields migration widens
// the validators to tolerate null defensively for documents written before
// that normalization existed. This test creates each entity type with every
// affected field left nil and confirms both that Create succeeds and that
// the round-tripped entity reads back with a usable non-nil empty
// map/slice — not just "doesn't error".
package mongo

import (
	"context"
	"testing"

	"github.com/xraph/warden/assignment"
	"github.com/xraph/warden/checklog"
	"github.com/xraph/warden/id"
	"github.com/xraph/warden/permission"
	"github.com/xraph/warden/policy"
	"github.com/xraph/warden/relation"
	"github.com/xraph/warden/resourcetype"
	"github.com/xraph/warden/role"
)

func TestMongo_CreateWithNilMetadata_RoundTrips(t *testing.T) {
	s, cleanup := setupMongo(t)
	defer cleanup()
	ctx := context.Background()

	t.Run("Role", func(t *testing.T) {
		r := &role.Role{ID: id.NewRoleID(), TenantID: "t1", Name: "Editor", Slug: "editor-nilmeta"}
		if r.Metadata != nil {
			t.Fatalf("test setup: expected nil Metadata")
		}
		if err := s.CreateRole(ctx, r); err != nil {
			t.Fatalf("CreateRole with nil Metadata: %v", err)
		}
		got, err := s.GetRole(ctx, "t1", r.ID)
		if err != nil {
			t.Fatalf("GetRole: %v", err)
		}
		if got.Metadata == nil || len(got.Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got.Metadata)
		}
	})

	t.Run("Permission", func(t *testing.T) {
		p := &permission.Permission{ID: id.NewPermissionID(), TenantID: "t1", Name: "nilmeta:read", Resource: "doc", Action: "read"}
		if err := s.CreatePermission(ctx, p); err != nil {
			t.Fatalf("CreatePermission with nil Metadata: %v", err)
		}
		got, err := s.GetPermission(ctx, "t1", p.ID)
		if err != nil {
			t.Fatalf("GetPermission: %v", err)
		}
		if got.Metadata == nil || len(got.Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got.Metadata)
		}
	})

	t.Run("Assignment", func(t *testing.T) {
		r := &role.Role{ID: id.NewRoleID(), TenantID: "t1", Name: "AssnRole", Slug: "assn-nilmeta"}
		if err := s.CreateRole(ctx, r); err != nil {
			t.Fatalf("setup CreateRole: %v", err)
		}
		a := &assignment.Assignment{ID: id.NewAssignmentID(), TenantID: "t1", RoleID: r.ID, SubjectKind: "user", SubjectID: "nilmeta-user"}
		if err := s.CreateAssignment(ctx, a); err != nil {
			t.Fatalf("CreateAssignment with nil Metadata: %v", err)
		}
		got, err := s.GetAssignment(ctx, "t1", a.ID)
		if err != nil {
			t.Fatalf("GetAssignment: %v", err)
		}
		if got.Metadata == nil || len(got.Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got.Metadata)
		}
	})

	t.Run("Relation", func(t *testing.T) {
		tup := &relation.Tuple{
			ID: id.NewRelationID(), TenantID: "t1",
			ObjectType: "document", ObjectID: "nilmeta-doc", Relation: "viewer",
			SubjectType: "user", SubjectID: "nilmeta-user",
		}
		if err := s.CreateRelation(ctx, tup); err != nil {
			t.Fatalf("CreateRelation with nil Metadata: %v", err)
		}
		got, err := s.ListRelations(ctx, &relation.ListFilter{TenantID: "t1", ObjectID: "nilmeta-doc"})
		if err != nil {
			t.Fatalf("ListRelations: %v", err)
		}
		if len(got) != 1 {
			t.Fatalf("expected 1 relation, got %d", len(got))
		}
		if got[0].Metadata == nil || len(got[0].Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got[0].Metadata)
		}
	})

	t.Run("Policy", func(t *testing.T) {
		// Subjects, Actions, Resources, Conditions, Obligations, Metadata
		// are all left nil on purpose.
		p := &policy.Policy{ID: id.NewPolicyID(), TenantID: "t1", Name: "nilmeta-policy", Effect: policy.EffectAllow, IsActive: true}
		if err := s.CreatePolicy(ctx, p); err != nil {
			t.Fatalf("CreatePolicy with nil Metadata/slices: %v", err)
		}
		got, err := s.GetPolicy(ctx, "t1", p.ID)
		if err != nil {
			t.Fatalf("GetPolicy: %v", err)
		}
		if got.Metadata == nil || len(got.Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got.Metadata)
		}
		if got.Subjects == nil || got.Actions == nil || got.Resources == nil || got.Conditions == nil || got.Obligations == nil {
			t.Errorf("expected nil-on-write slices to round-trip as non-nil empty, got "+
				"Subjects=%v Actions=%v Resources=%v Conditions=%v Obligations=%v",
				got.Subjects, got.Actions, got.Resources, got.Conditions, got.Obligations)
		}
	})

	t.Run("ResourceType", func(t *testing.T) {
		// Relations, Permissions, Metadata are all left nil on purpose.
		rt := &resourcetype.ResourceType{ID: id.NewResourceTypeID(), TenantID: "t1", Name: "nilmeta-doctype"}
		if err := s.CreateResourceType(ctx, rt); err != nil {
			t.Fatalf("CreateResourceType with nil Metadata/slices: %v", err)
		}
		got, err := s.GetResourceType(ctx, "t1", rt.ID)
		if err != nil {
			t.Fatalf("GetResourceType: %v", err)
		}
		if got.Metadata == nil || len(got.Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got.Metadata)
		}
		if got.Relations == nil || got.Permissions == nil {
			t.Errorf("expected nil-on-write slices to round-trip as non-nil empty, got Relations=%v Permissions=%v", got.Relations, got.Permissions)
		}
	})

	t.Run("CheckLog", func(t *testing.T) {
		// MatchedBy, Obligations, Metadata are all left nil on purpose.
		e := &checklog.Entry{
			ID: id.NewCheckLogID(), TenantID: "t1", SubjectKind: "user", SubjectID: "nilmeta-user",
			Action: "read", ResourceType: "document", ResourceID: "nilmeta-doc", Decision: "allow",
		}
		if err := s.CreateCheckLog(ctx, e); err != nil {
			t.Fatalf("CreateCheckLog with nil Metadata/slices: %v", err)
		}
		got, err := s.GetCheckLog(ctx, "t1", e.ID)
		if err != nil {
			t.Fatalf("GetCheckLog: %v", err)
		}
		if got.Metadata == nil || len(got.Metadata) != 0 {
			t.Errorf("Metadata = %v, want non-nil empty map", got.Metadata)
		}
		if got.MatchedBy == nil || got.Obligations == nil {
			t.Errorf("expected nil-on-write slices to round-trip as non-nil empty, got MatchedBy=%v Obligations=%v", got.MatchedBy, got.Obligations)
		}
	})
}
